const BIRDS = 
[
    'Alcids',
    'Bee-eaters',
    'Cassowaries',
    'Colies',
    'Cormorants',
    'Cuckoo-Roller',
    'Cuckoos',
    'Falcons',
    'Frigatebirds',
    'Grebes',
    'Herons',
    'Hornbills',
    'Hummingbirds',
    'Kiwis',
    'Loons',
    'Ostriches',
    'Owls',
    'Oystercatchers',
    'Pelicans',
    'Penguins',
    'Plovers',
    'Water Rails',
    'Corn crake',
    'Moorhen',
    'Sandgrouse',
    'Seriemas',
    'Storks',
    'Swans',
    'Geese',
    'Ducks',
    'Swifts',
    'Tinamous',
    'Todies',
    'Tropicbirds',
    'Trogons'
];
    
const INSECTS = 
[
    'alderflies',
    'amblypygids',
    'ant lions',
    'ants',
    'caddisflies',
    'cicadas',
    'cockroaches',
    'daddy-longlegs',
    'damselflies',
    'diplurans',
    'dragonflies',
    'false scorpions',
    'grasshoppers',
    'hangingflies',
    'humpbacked flies',
    'ice crawlers',
    'insect eggs',
    'isopods',
    'jumping bristletails',
    'katydids',
    'locusts',
    'mantispids',
    'mosquitoes',
    'moths',
    'scorpionflies',
    'scorpions',
    'spiders',
    'stick insects',
    'wasps',
    'webspinners',
    'whiteflies',
    'wind-scorpions'
];
    
const FISH =
[
    'shrimp',
    'mantis shrimp',
    'bullhead sharks',
    'bowfin',
    'bonytongues',
    'catfishes',
    'chimaeras',
    'cods',
    'cow sharks',
    'cowfishes',
    'damselflies',
    'dories',
    'filefishes',
    'flatfishes',
    'flying gurnards',
    'garfishes',
    'grenadiers',
    'hakes',
    'john dories',
    'killifishes',
    'lampreys',
    'milkfish',
    'minnows',
    'needlefishes',
    'opahs',
    'pikeperches',
    'piranhas',
    'puffers',
    'salmon',
    'saw sharks',
    'sea horses',
    'skate fish',
    'snipefishes',
    'sole',
    'sticklebacks',
    'stingrays',
    'surgeonfishes',
    'tarpons',
    'trunkfishes',
    'Oceanic dolphins',
    'Porpoises',
    'Belugas',
    'narwhals',
    'Sperm whales',
    'Beaked whales',
    'Blue whale',
    'Humpback Whale',
    'Gray whale',
    'bowhead whales'
];
    
const LANDANIMALS = 
[
    'cuscuses',
    'Red panda',
    'Walrus',
    "Leadbeater's possum",
    'Dogs',
    'wolves',
    'foxes',
    'coyotes',
    'jackals',
    'Cats',
    'Hyenas',
    'Mongooses',
    'Weasels',
    'ferrets',
    'badgers',
    'otters',
    'Eared seals',
    'sea lions',
    'True seals',
    'Raccoons',
    'coatis',
    'kinkajous',
    'Bears',
    'Agamas',
    'chameleons',
    'Geckos',
    'Anoles',
    'iguanas',
    'Skinks',
    'Whiptails',
    'tegus',
    'Monitor lizards',
    'Three-toed sloths',
    'Armadillos',
    'Two-toed sloths',
    'Anteaters',
    'tamanduas',
    'Pronghorns',
    'Cattle',
    'goats',
    'sheep',
    'antelopes',
    'Gazelles',
    'Wildebeests',
    'Impalas',
    'Bison',
    'Muskox',
    'Water Buffalo',
    'Camels',
    'llamas',
    'alpacas',
    'vicuñas',
    'Deer',
    'Giraffes',
    'okapis',
    'Musk deer',
    'Pigs',
    'hogs',
    'Peccaries',
    'Hyraxes',
    'Hedgehogs',
    'gymnures',
    'Solenodons',
    'Tenrecs',
    'Golden moles',
    'Moles',
    'shrew Moles',
    'desmans',
    'Shrews',
    'water shrews',
    'Desmans',
    'moles',
    'Rabbits',
    'hares',
    'Pikas',
    'Marsupial mole',
    'Opossums',
    'Monito del monte',
    'Shrew opossums',
    'Quolls',
    'dunnarts',
    'Tasmanian devils',
    'Numbat',
    'Bandicoots',
    'bilbies',
    'Bilby',
    'Koalas',
    'Wombats',
    'Kangaroos',
    'wallabies',
    'tree-kangaroos',
    'pademelons',
    'quokkas',
    'Ringtail possums',
    'greater glider',
    'Rat-kangaroos',
    'Platypus',
    'Echidnas',
    'Sac-winged bats',
    'Mouse-tailed bats',
    'Bumblebee bat',
    'False vampire bats',
    'Horseshoe bats',
    'Leaf-nosed bats',
    'Vesper bats',
    'Free-tailed bats'
];
